### ISSUE TITLE
if content-type isn't application/json 'json_input' referenced before assignment

### ISSUE THREAD

**Issue by Charlie-Mindified** [Ge0rg3/flask-parameter-validation#10]
if content-type isn't application/json
json_input is never set but is still accessed on row 26 in parameter_validation.py.
throws error: UnboundLocalError: local variable 'json_input' referenced before assignment

`request_inputs = {
                Route: kwargs.copy(),
                Json: json_input,
                Query: request.args.to_dict(),
                Form: request.form.to_dict(),
                File: request.files.to_dict()
            }`
**example of solution**
`request_inputs = {
                Route: kwargs.copy(),
                Json: json_input if 'json_input' in vars() else None,
                Query: request.args.to_dict(),
                Form: request.form.to_dict(),
                File: request.files.to_dict()
            }`

**Comment by Ge0rg3** [comment]
Closed by #11, thanks again!
