### ISSUE TITLE
AttributeError raised when trying to get attribute from Delivery Type that wasn't provided to Request

### ISSUE THREAD

**Issue by d3-steichman** [Ge0rg3/flask-parameter-validation#18]
https://github.com/Ge0rg3/flask-parameter-validation/blob/d6d96817eb7d84eb960eefc5cf14f532c26c0af7/flask_parameter_validation/parameter_validation.py#L83

Error is thrown on call to .get() on Line 83 if Json() is expected (Optional[] or not) and no JSON body is provided when the request is hit through Flask

**Comment by Ge0rg3** [comment]
Hi @d3-steichman, please can you provide a simple example endpoint/code and I'll whip up a fix?

**Comment by Ge0rg3** [comment]
Should be resolved, please retest if possible 👍

**Comment by d3-steichman** [comment]
Didn't get a changes to test today, will let you know the verdict by EOD Eastern Time on Thursday, thanks!

**Comment by smt5541** [comment]
Sorry for the delay, this is resolved in latest version 😄

**Comment by Ge0rg3** [comment]
Great, thanks!
