### ISSUE TITLE
python 3.6 - AttributeError: module 'typing' has no attribute '_SpecialForm'

### ISSUE THREAD

**Issue by bincdianshangcun** [Ge0rg3/flask-parameter-validation#2]
When using under python3.6 env, I am getting this  error:

```AttributeError: module 'typing' has no attribute '_SpecialForm'```

is there anyway to work around it?

Thanks!

**Comment by Ge0rg3** [comment]
Interesting, will take a look later. Thanks!

**Comment by bincdianshangcun** [comment]
Thank you! 
I took a look at my 3.6 env, and notice there indeed isn't a _SpecialForm member in typing.py.

**Comment by Ge0rg3** [comment]
Hi, sorry for delay, this issue should now be resolved. As mentioned in [the release](https://github.com/Ge0rg3/flask-parameter-validation/releases/tag/v2.0.0), this bug required a near-full rewrite 😢   
Please can you retest and confirm?

**Comment by maishams** [comment]
retested and can confirm this works!

**Comment by Ge0rg3** [comment]
Thanks, have tested myself too so will close.
