### ISSUE TITLE
Support multiple values for same parameter

### ISSUE THREAD

**Issue by summersz** [Ge0rg3/flask-parameter-validation#23]
If multiple values are passed for the same parameter using query parameters they are typically passed as ```?param=1&param=2``` or ```?param=1,2```
Can either of these methods be supported to parse them as a list?
It is easy enough to use and define the comma-separated list style as a string ```param: str = Query()``` and then split it, but thought I would suggest it as a feature request anyway.

**Comment by summersz** [comment]
Hi @Ge0rg3, this behavior is also seen with form and file data. I have created a helper function to transform the MultiDict into a dict with lists, rather than using the to_dict() method, for Query, Form and File inputs.  Which is working, however with one caveat when only a single value is sent.

Since there is no way of checking if the data received is intended to be an array or not, if there is only one value the function will always return that as a single value and not an array of length 1.

There are two ways I see to handle this:
1. You either define your parameter like param: List[str] | str = Query(), and handle the two instance types in the function
2. The validate function will accept and transform a single value into a list if a List type is expected.

What do you think to option 2?

```python
def _to_dict_with_lists(self, multi_dict: ImmutableMultiDict) -> dict:
    dict_with_lists = {}
    
    for key, values in multi_dict.lists():
        list_values = []
        for value in values:
            if isinstance(value, str):
                list_values.extend(value.split(","))
            else:
                list_values.append(value)
        dict_with_lists[key] = (
            list_values[0] if len(list_values) == 1 else list_values
        )
    
    return dict_with_lists
```

**Comment by Ge0rg3** [comment]
Hey @summersz, thanks for the indepth analysis on the issue. I think option 2 sounds better and is easier for users than option 1 👍
