### ISSUE TITLE
2.2.0 breaks form parameters

### ISSUE THREAD

**Issue by dkassen** [Ge0rg3/flask-parameter-validation#29]
Howdy y'all.

I just updated to 2.2.0 today and it's breaking some pretty simple unittests:

test:
```python
 def test_login_with_correct_password(self):
        data = {"email": "string-email@example.com", "password": "Pass-Word-1"}
        response = app.test_client().post("/login", data=data)
        print(response.status, response.text)
        assert response.status == "200 OK"
```
That print statement gives me:
`400 BAD REQUEST {"error":"Parameter 'email' must be type 'str'"}`

endpoint:
```python
@blueprint.route("/login", methods=["POST"])
@ValidateParameters()
def login(
    email: str = Form(pattern=email_regex),
    password: str = Form(max_str_length=32, min_str_length=8)
):
    pass
```

I traced it down to a [change](https://github.com/Ge0rg3/flask-parameter-validation/pull/24/files#diff-b406cf04c0651be0cb01c202a762120dafe5b64cc2ea5fb69876dc554f7f178bR59) in #24, replacing `request.form.to_dict()` with the new `self._to_dict_with_lists(request.form)`
Comparing the two:
`print(self._to_dict_with_lists(request.form), request.form.to_dict()`
gives
`{'email': ['user0@example.com'], 'password': ['Pass-Word-1']} {'email': 'user0@example.com', 'password': 'Pass-Word-1'}`

As can be seen, the parameter values are now wrapped in Lists.

**Comment by Ge0rg3** [comment]
🤦 my bad, thank you for catching this! Will merge and release tomorrow

**Comment by dkassen** [comment]
Thanks @Ge0rg3!
