### ISSUE TITLE
Conversion of empty string to None

### ISSUE THREAD

**Issue by summersz** [Ge0rg3/flask-parameter-validation#35]
For query and form data, null values are transmitted as empty strings.

I would like to suggest a method to convert these to None during the convert function of the Query class.

I think the user would need to specify that this is the functionality they want.  I am thinking either checking for Union[str, None] as the type or adding an extra attribute like allow_none=True.

**Comment by Ge0rg3** [comment]
Got it... I guess checking for `Union[str,None]` has the same effect as just setting as `Optional[str]`, and then either returning `None` or a `str`?

**Comment by summersz** [comment]
yes, that's a nicer way to declare it.

**Comment by summersz** [comment]
Having thought about this a little more I think passing an option would be a better solution, rather than relying on ```Optional[str]```, as this could lead to unexpected behaviour for users.  

I was thinking ```blank_none=True``` and this would set a Falsy user_value to None in the validate function. 
```
# If blank none is true and the input is Falsy, set to None
if expected_delivery_type.blank_none and not user_input:
    user_input = None
```
This would precede where the default values are set, so would also work in this instance. i.e. if an empty string is passed with the blank_none setting and a default value it would be set to None and then the default logic would pick it up and set it to the default value.

Let me know what you think, I can raise a pull request.

**Comment by Ge0rg3** [comment]
For sure blank_none could be a good option.. What unexpected behaviour do you reckon using `Optional[str]` may cause?

**Comment by summersz** [comment]
One example I have is using a search string query parameter.  I am using the same endpoint to retrieve html on the first load as well as getting specific data based on the search query. 

I first check if the search query is None which indicates this is the first page loads so retrieve all the html
    
If I get a search query (which can be an empty string) I then retrieve an html fragment, so in this instance I wouldn't want the empty string to be converted to None.

```
@endpoint.get("")
@ValidateParameters()
def index(search: Optional[str] = Query(default=None)):
    if search is None: # first load
        return full_html
    else:
        return partial_filtered_html
```

Although there are workarounds for this I don't think it would be the expected default behaviour of Optional[] to return None, so could trip people up trying to do something like this.

**Comment by vishalgupta1987** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
ConorHK, @maxi-marufo, @PaulWBrassard, @snd, @alexandarp, @mryayaa, @s1nack-dev, @dfdgsdfg, @basicScandal, @catchingknives, @Marneus68, @galonsky, @zadm, @cudgel, @manudarah, @dnavarrom, @hearsilent, @pequalsmp, @c4nc, @marcusficner

**Comment by smt5541** [comment]
What are your thoughts on `blank_none` defaulting to `True` to keep things backwards compatible?

Additionally, a variable in current_app.config could be set by end-users to override this default globally in their app, while still allowing the use of `blank_none` to change the behavior for individual parameters.

**Comment by smt5541** [comment]
Wanted to follow up on the above - if there aren't any further comments, I'll go ahead and implement a `blank_none` option that defaults to `True` with a variable in `current_app.config` for overriding this globally for an app.
