### ISSUE TITLE
Allow passing a custom function as a validator

### ISSUE THREAD

**Issue by Garcel** [Ge0rg3/flask-parameter-validation#5]
I would find useful to pass a function acting as a validator to the Parameter. This way i would be able to fully customize the behavior in some cases.

That function could:
  - Return a bool indicating whether the validation has been passed or not.
  - Raise a ValueError when that validation wasn't succesful.

Maybe I could help with this If you want.

**Comment by Ge0rg3** [comment]
Hey, thanks for the suggestion -- definitely a good idea! I'm quite busy for the next ~1.5 months but will look into implementation after, unless you want to raise a PR 😄

**Comment by Garcel** [comment]
Hi, sure I would be glad to help. I'll be raising a PR next week

**Comment by Ge0rg3** [comment]
Closed by #6, thanks again!
